name: Keycloak security
rating: 5
imageUrl: https://github.com/msa-ez/template-spring-boot-3/assets/123912988/db634ed7-e2b6-4708-aa62-1a668515bb15
templateName: keycloak-security
description: Keycloak security description
